:toc: macro
toc::[]





= *1. Project Introduction. Statement of Purpose*

Existing systems to manage queues and turns consists only in the assignation of a number without any associated logic that improves user experience and give value to user and to queue owner.

Classic systems do not allow to know at what time will be each turn. In addition, clients only can consult queue status if he stays at the queue location. This provoke a bad user experience because he must to stay in the queue all waiting time. Besides, in an amount of cases, this causes that some users leave the queue because the long waiting time, provoking the loss of the sales.

Ideally the users of the queue have to be able to know at what hour could be its turn. It is very important because he can improve its time and he will need to wait in the queue and only go when its time reaches.

Besides, to facilitate that the user has not to be in the queue waiting its turn, he can consult the queue status at any device that he can have. (for example a mobile phone, tablet,  ..)

As value added, queue owners will be able to prioritize users at the queue to have the possibility of creating marketing campaigns.

A successful solution would be to improve user experience facilitating that the user has not to be in the queue waiting its turn.

= *2. Objectives*

The objectives of the project are:

= *3. First Steps Analysis*

This is the First Steps Analysis presentation used to present and validate our understanding of the User Stories and behaviour of the future solution with customer.

= *4. User Stories*

As the first objective of Jump the Queue component is to improve the time management of the user, providing the needed functionalities to do so.

The solution focus on this premise and has to facilitate the process of accessing and consulting to the queue.

Roughly, the entire process that a user will follow to obtain and consult the access code of a queue will be:





The main actors that will interact with jump the queue component will be the following:

- *User* : It is an internal user of the external system that creates the queue and it will have privilege access to the queue.

- *Visitor* : User of the queue component that does not exist in the external system that created the queue.

- *Owner* : User that manages the queue.



In the next points, we can see the details of the user stories that define the minimum functionality of Jump the Queue component.

We can see the proposed user story map at the following figure.



== *Epic 1. Get a number*

This epic contains all needed functions that allow users to get a number for entering in the queue.



As part of the process, the epic must implement:

1º Accept terms &amp; conditions.

2º Register in the queue. As part of this process the component must validate the information.

3º Obtain the code to access the queue.



The user stories that define this epic are:

=== User story 1. Accept terms &amp; conditions

|==================
| Story Narrative | Accept terms &amp; conditions | Priority | 5 
| As | | Size |
| I need to | accept terms and conditions | Dependency |
| So that | I can access jump the queue system ||
| Acceptance Criteria | - Terms and conditions will be configurable and the system must show this text. - The system will ask to accept terms and conditions before getting an access code. ||
|==================




=== User story 2. Verify information

|==================
| Story Narrative | Verify information | Priority | 5 
| As | | Size 
| I need | my telephone number or email to be verified | Dependency 
| So that | their validity will be confirmed 
| Acceptance Criteria | - User has to receive an email or a SMS with a validation code. - The system will only allow the access to users that input this validation code.  
|==================




=== User story 3. Consent information

|==================
| Story Narrative | Consent information | Priority | 1 
| As | | Size 
| I want to | give my permission for the use of my personal information | Dependency 
| So that | I can received commercial notices 
| Acceptance Criteria | - This functionality can be activated or de-activated. - If the user gives its permission, the system must save this information.  
|==================




=== User story 4. Register

|==================
| Story Narrative | Register | Priority | 10 
| As | | Size 
| I want to | register to obtain an access code for the queue | Dependency 
| So that | I get an access code 
| Acceptance Criteria | - User can inform a phone, email and a Name. - The name is mandatory. - The phone or the email have to be informed. - The phone or the email have to be confirmed. - The access code will be formatting as &quot;Q&quot; plus a number between 0 to 999. - The access code will be the next free number. If the number reaches 999, the number continues with 0. - The email, phone cannot be repeated in more than one non-attended turns. 
|==================




=== User story 5. Priority access

|==================
| Story Narrative | Priority access | Priority | 5 
| As | internal user | Size 
| I want to | get priority access code to the queue | Dependency 
| So that | I will be attended earlier 
| Acceptance Criteria | -  The access code will be formatting as &quot;A&quot; plus a number between 0 to 999. - The access code will be the next free number. If the number reaches 999, the number continues with 0. 
|==================




== *Epic 2. Consult the queue*

It contains all functions that permit to order and to consult the status of the queue.

The user stories that define this are:

=== User story 6. Consult Queue

|==================
| Story Narrative | Consult queue | Priority | 10 
| As | | Size 
| I want to | | Dependency 
| So that | 
| Acceptance Criteria | - The system only returns the non-attended turns of the queue. - The list will be ordered by the time when the ticket was taken, except in the case that the access code will be of the form &quot;A&quot; + number that will be first (priority access). - The list must return the following information: Access code, estimated time and Name. - The user can consult the status of the queue although he has left of the system. 
|==================




=== User story 7. Waiting time

|==================
| Story Narrative | Waiting time | Priority | 10 
| As | | Size 
| I want to | | Dependency 
| So that | 
| Acceptance Criteria | - The system has to calculate the estimated time with the following formula: current hour + (Sum(The last ten attention time)/nº of attended turn counted)*(number of non-attended turns in the queue before this). - The number cannot be less than a configurable value. - The attention time is the difference between the start time and the end time.  
|==================




== *Epic 3. Manage queue*

It contains all functions that allow to manage the queue in order to configure and attend active turn.

The user stories that define this are:

=== User story 8. Configure queue

|==================
| Story Narrative | Configure queue | Priority | 5 
| As | | Size 
| I want to | | Dependency 
| So that | 
| Acceptance Criteria | - The system allows to configure a logo and description. - Jump the queue front shows the logo and description   
|==================




=== User story 9. Attend queue

|==================
| Story Narrative | Attend queue | Priority | 10 
| As | | Size 
| I need to | | Dependency 
| So that | 
| Acceptance Criteria | - The turn has to be the first in the queue that is non-attended. - The system must save: - At the previous turn: Save the current time as end time - At the new turn: Save the current time as start time  
|==================


= *5. Site Map*

We proposed the following sitemap and screen structures to support the requirements that solution shall fulfill.





1º Select Queue. This step will not be a screen and represents the operation to be followed by a user to enter Jump the Queue.

2º Request/ Insert code. This functionality represents the process to be followed by a user to obtain a ticket number. The proposed screen will only apply to visitor users because existing users will have a direct access to step 3.



3º Assigned Order / Show Queue. Here, the user can consult its number and the list of people in the queue.





Finally, the owner of the queue can consult and pass the turn with the consult screen and with a button at the screen or pressing a physical button.







= *6. Entity relationship diagram*

Starting from the list of user stories, we found the below entities to support them.







Each entity will content the following information:



|==================
| Visitor Information 
| It contains the personal information of the visitors who gave the permission to use it 
| Name | String 
| Telephone | TelephoneType 
| Email | EmailType 
|==================


|==================
| Terms and conditions 
| It describes the Terms and conditions that the user must accept to use the queue 
| Description | String 
|==================


|==================
| Queue owner 
| It contains information for the users that can manage queues 
| User | userIdType 
| Name | String 
| Email | EmailType 
| Password | PasswordType 
|==================


|==================
| Queue 
| It contains the information that describes a queue 
| Description | String 
| Logo | Image 
|==================


|==================
| Access code 
| It contains the list people that are in the queue and their information. 
| Id_code | String. Assigned code. PK 
| Name | String 
| Email | EmailType 
| Telephone | TelephoneType 
| CreationTime | Time (HH:MM). The hour when the user got the turn 
| StartTime | Time (HH:MM). The hour when the attendance of the user starts 
| EndTime | Time (HH:MM). The hour when the attendance of the user ends 
| EstimatedTime | Time (HH:MM). The hour which the system estimated when the user will be attended 
|==================




= *7. Bounded context*

In this point, we will define the bounded context of the final solution.

In the figure below we have three domains, one for each related Epic.

-      Obtain Access code domain: As we saw at epic chapter, this domain contains the required logic to get a turn in the queue. The related entities are:

-      Consult queue status domain: It has the needed logic to check turn status. This is supported by the entities:

-      Manage queue domain: This domain contains all functionalities to configure the queues and their owners.







= *8. Glossary of terms*

|==================
| Term | Description 
| Access code | This is the turn number assigned to a person 
| Validation code | It is a code used to confirm the validity of the email or telephone number informed by the user 
| Estimated time | Stands for the time that the system calculates when the person in the queue will be attended 
| Attention time | This is the time that it takes for a user to be attended. It is calculated as the difference between the start and the end of the attention 
| Priority access | It is the access granted to privileged users so they can be attended earlier 
|==================


== Recent space activity

           Luisa Perez Devesa       Jump the queue Home  updated Feb 02, 2018 view change          Félix Murillo García-bermejo       Jump the queue Home  updated Feb 01, 2018 view change      

== Space contributors

{&quot;mode&quot;:&quot;list&quot;,&quot;scope&quot;:&quot;descendants&quot;,&quot;limit&quot;:&quot;5&quot;,&quot;showLastTime&quot;:&quot;true&quot;,&quot;order&quot;:&quot;update&quot;,&quot;contextEntityId&quot;:2163154}



